name:                haski
version:             0.1.0.0
github:              "OctopiChalmers/haski"
license:             BSD3
author:              "Octopi"
maintainer:          "nacval@chalmers.se"
copyright:           "2020 Octopi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

dependencies:
- base >= 4.7 && < 5
- ghc-typelits-extra >= 0.3.1
- mtl >= 2.2.0
- containers >= 0.6
- ghc-typelits-natnormalise >= 0.6
- pretty >= 1.0
- array
- bytestring
- cereal
- constraints
- language-c99-simple
- language-c99

default-extensions:
  - GADTs
  - DataKinds
  - TypeOperators
  - TypeApplications
  - ScopedTypeVariables
  - ExistentialQuantification
  - PatternSynonyms

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -fdefer-type-errors
  - -funclutter-valid-hole-fits
  - -fmax-relevant-binds=3
  - -freduction-depth=0

library:
  source-dirs: src
